heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
    - http://kibana:5601
    - http://products-svc:4000

# ping
- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana
    - apm
    - metricbeat

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: 'elastic'
  password: 'changeme'